### ISSUE TITLE
Failed to resolve: com.google.modernstorage:modernstorage-permissions:1.0.0-alpha06

### ISSUE THREAD

**Issue by gabriel-TheCode** [google/modernstorage#97]
## Error when building app with modernstorage
```
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsCvsDebug'.
> Could not resolve all files for configuration ':app:cvsDebugCompileClasspath'.
   > Failed to transform modernstorage-storage-1.0.0-alpha06.aar (com.google.modernstorage:modernstorage-storage:1.0.0-alpha06) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find modernstorage-storage-1.0.0-alpha06.aar (com.google.modernstorage:modernstorage-storage:1.0.0-alpha06).
        Searched in the following locations:
            https://plugins.gradle.org/m2/com/google/modernstorage/modernstorage-storage/1.0.0-alpha06/modernstorage-storage-1.0.0-alpha06.aar

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:dataBindingMergeDependencyArtifactsCvsDebug'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
...

```

## To Reproduce
1. Add 
 implementation("com.google.modernstorage:modernstorage-permissions:1.0.0-alpha06")
 implementation("com.google.modernstorage:modernstorage-storage:1.0.0-alpha06")
2. Build app
3. Run app

## Environment:
 - Android OS version: 13 beta2
 - Target SDK version 31
 - Device: Google Pixel 6
 - ModernStorage version: 1.0.0-alpha06

## Additional context
mavenCentral() added in build.gradle

**Comment by rafsanjani** [comment]
Try using the Bill of Materials;

```
 implementation("com.google.modernstorage:modernstorage-bom:1.0.0-alpha06")
 implementation("com.google.modernstorage:modernstorage-permissions")
 implementation("com.google.modernstorage:modernstorage-storage")
```
